### ISSUE TITLE
Crash in stated up

### ISSUE THREAD

**Issue by minuzzz** [Ephys/TinkersSteelworks#95]
I try very hard to install TSteelworks mod into game but i can't
I try ( 1.1.0-14 ),( 1.1.0 ), (1.1.0-6)... I mean i try alot of way but alway dead end
I have download Cookiecore latest version and Mantle but is useless.
If it a bug, then fix it.. Or if a do something wrong, then show me how to fix that.
thanks
![bug](https://cloud.githubusercontent.com/assets/12207000/7440291/7130f764-f0d5-11e4-97f3-fccf8b798400.jpg)

**Comment by Ephys** [comment]
What's the crash report saying ?

**Comment by DcNdrew** [comment]
I don't know if it's the same crash, but I have one too:
http://pastebin.com/n0MTSDW7

**Comment by Ephys** [comment]
If that's the right crash report, it's very strange because that's something I'm sure I fixed in the latest TSteelworks

**Comment by DcNdrew** [comment]
Some months ago that worked but after that I upgraded many mods include Forge. Could be that?

**Comment by Ephys** [comment]
It was definitely fixed, maybe I forgot to build it. I just launched a new build for both cookiecore and tsteelworks, these should work

**Comment by minuzzz** [comment]
Thank for reply @Ephys 
But i have download new version and had same crashed
I download : 
TSteelworks-1.7.10-1.1.0-6 
CookieCore-1.7.10-1.3.1-7
But still crash
This is Crash Report:
https://docs.google.com/document/d/1JDdW3fEj9BbBWKjGoNbUYqCGAvJL7upRd19xDcNeXkY/edit

**Comment by medsal15** [comment]
@minuzzz I had the same crash until I removed CookieCore and Tinker's Steelworks

**Comment by minuzzz** [comment]
@medsal15 : Ofcause. We can removed it to solve this problem but i really like this mod. So i keep waiting for Ephys answer

**Comment by medsal15** [comment]
@minuzzz I understand. Tinker's Steelwork adds a cool way to make steel without making it OP.

**Comment by minuzzz** [comment]
@medsal15 : Yeah. I want to complete sieve and smelt system
Tinker constuct is not " Smart " to complete it

**Comment by Ephys** [comment]
> TSteelworks-1.7.10-1.1.0-6 
CookieCore-1.7.10-1.3.1-7

You're going to have to use the latest version otherwise I'm not going to be able to find what's wrong as the source code changed 

Latest TSteelworks is currently number 16, not 6: http://tehnut.info/jenkins/job/TSteelworks/16/
Latest CookieCore is version 8 http://tehnut.info/jenkins/job/CookieCore/8/

**Comment by medsal15** [comment]
@Ephys It works! Thank you!

**Comment by minuzzz** [comment]
@Ephys : That work instantly
Ty bro. I'm enjoy it
